[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "fastify"
rootDirectory = "/fastify"

